### ISSUE TITLE
Middleware synchronous?

### ISSUE THREAD

**Issue by jserpapinto** [lionix-team/vue-route-middleware#3]
Hey,

Is it possilble to make the middleware synchronous?
I'm trying your package and it seems that all functions start in the order they were declared, but they all run asynchronously.

Thanks!

**Comment by vaawebdev** [comment]
@jserpapinto The problem is that the vue guards are asynchronous and the middleware is registered in the guard. I have tried to implement the resolver one after another but it leads to a problem when the router has been resolved and the page is rendered but the middleware stack is still running... If you have any solution to this please make PR I will merge it with pleasure!

**Comment by erisrayanesh** [comment]
@vaawebdev please look at the following code.
```js
router.beforeEach((fro, to, next) => {
    setTimeout(()=>{
        next();
    }, 10000);
});
```

After 10 seconds the next method will be called and the route will be resolved. Would you please clarify the problem you mentioned in your  last comment . I just can't understand what's the relation between page resolve and page render

**Comment by karakhanyans** [comment]
@erisrayanesh Sure! the next function in proxying Vue-Router's next function. If the route was resolved (in the case of your example it will be resolved when timeout reaches) and you put arguments like another route name into the next function (for example if you want your app to be redirected) you will get a weird console error, as well as window history, which will be messed up. I tried to make some workarounds making the middleware handler async, but the router itself does not support async guards.

**Comment by vaawebdev** [comment]
@erisrayanesh Sure! The next function is proxying Vue-Router's next function. If the route was resolved (in the case of your example it will be resolved when timeout reaches) and you put arguments like another route name into the next function (for example if you want your app to be redirected) you will sometimes get a weird console error, as well as window history, which will be messed up. I tried to make some workarounds making the middleware handler async, but the router itself does not support async guards.

**Comment by erisrayanesh** [comment]
@vaawebdev How about AdonisJs approach on middleware pattern? it's very similar to what we want except that they could process response too and we can skip it and just keep focus on request.

[This](https://github.com/poppinss/co-compose/blob/master/src/Runnable.ts) file and repo is the library used by AdonisJs for managing the execution of a middleware stack. It worth a review

**Comment by vaawebdev** [comment]
@erisrayanesh I think releasing a major version of this with typescript and async/sync middleware support. Thanks for your feedback, I will see if I can use some of those approaches...
